### ISSUE TITLE
Not production ready?

### ISSUE THREAD

**Issue by frblondin** [sergezhigunov/Hangfire.EntityFramework#1]
We are considering using Hangfire... and need to be compatible with both SqlServer and Oracle. I saw your project and believe it is very promising. I quickly went through the code and it looks great. If we decide to use Hangfire we might end up be willing to contribute to your project.

I saw the description of the project where you are saying that this is not ready for production. I wanted to know from your perspective if you identified existing things that should be reviewed/fixed/improved/...?

**Comment by sergezhigunov** [comment]
Thank you for your interest.

There are a few problems in the current version.
* Low `IMonitoringApi` implementation performance
* Low queue processing performance
* Potentially incorrect behavior of distributed locks
* Non-optimal implementation of the `JobStorageTransaction` 
* Potentially concurrency issues caused by usage of `DbSetMigrationsExtensions.AddOrUpdate` methods

I plan to fix this problems and release a stable ready-to-production version at the end of December this year.

Any comments, suggestions and contributions are welcome. I will be very appreciated for any feedback.

**Comment by frblondin** [comment]
Thanks for your response.

Looking forward to contributing to the project... need a validation from my team first!
